name: Pull PurpleAir Data

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:  # Allow manual triggers

jobs:
  pull-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for git operations
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    
    - name: Create data directories
      run: |
        mkdir -p data/raw
        mkdir -p data/processed
    
    - name: Pull PurpleAir data
      env:
        PURPLEAIR_KEY: ${{ secrets.PURPLEAIR_KEY }}
      run: python scripts/pull_data.py
    
    - name: Process and store data
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        GCP_CREDS: ${{ secrets.GCP_CREDS }}
      run: python scripts/process_data.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update PurpleAir data [skip ci]" && git push) 